### ISSUE TITLE
询问一下如何抓取此请求的

### ISSUE THREAD

**Issue by WanCixiong** [BlacK201/lol-tencent-daily-purchase#1]
https://apps.game.qq.com/daoju/igw/main.....
请问这个URL是如何抓取的？

**Comment by BlacK201** [comment]
你好，这个URL是通过对客户端抓包获取到的

**Comment by WanCixiong** [comment]
首先，我十分感谢您的回复！
个Python初学者，请问是如何对客户端抓包，我只简单了解过Wireshark以及FD，但我并不会使用，Wireshark抓取到了但内容是乱码，我不知如何下手，是否可以指点一下？

**Comment by BlacK201** [comment]
你好，弄这个东西是大概一年前的事了，具体细节我也不太记得清，我记得我是强制LOL客户端走了Fidder的代理进行的抓包。

**Comment by WanCixiong** [comment]
感谢您的回复
